cubes:
  - name: products
    sql_table: public.products
    data_source: default

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
        public: true

      - name: name
        sql: name
        type: string

      - name: size
        sql: size
        type: string

    measures:
      - name: count
        type: count
        title: '# of products'

      - name: price
        type: sum
        title: Total USD
        sql: price_usd

    pre_aggregations:
    # Pre-aggregation definitions go here.
    # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
